cryptos = {
    'Bitcoin': 'BTC',
    'Ethereum': 'ETH',
    'Litecoin': 'LTC',
    'Ripple': 'XRP',
    'Bitcoin Cash': 'BCH',
    'Cardano': 'ADA',
    'Stellar': 'XLM',
    'NEM': 'XEM',
    'IOTA': 'MIOTA',
    'Monero': 'XMR',
    'EOS': 'EOS',
    'TRON': 'TRX',
    'Tether': 'USDT',
    'Bitcoin Gold': 'BTG',
    'Dash': 'DASH',
    'Nano': 'XRB',
    'Litecoin Cash': 'LTC',
    'VeChain': 'VEN',
    'Qtum': 'QTUM',
    'OmiseGO': 'OMG',
    'Zcash': 'ZEC',
    'Bitcoin SV': 'BSV',
    'Ethereum Classic': 'ETC',
    'Monero Classic': 'XMC',
    'OmiseGO Classic': 'OMG',
    'Zcash Gold': 'ZEC',
    'Nano S': 'NANO',
    'Bitcoin Diamond': 'BCD',
    'Monero Original': 'XMR',
    'Litecoin Gold': 'LTC',
    'Ethereum Gold': 'ETG',
    'Bitcoin Cash ABC': 'BCHABC',
    'Bitcoin Cash SV': 'BSV',
    'Bitcoin Cash Testnet': 'BCH',
    'Bitcoin Cash Testnet Cash': 'BCH',
    'Bitcoin Cash Testnet Cash ABC': 'BCHABC',
    'Bitcoin Cash Testnet Cash SV': 'BSV',
    'Bitcoin Cash Testnet Cash SV ABC': 'BSV',
    'Bitcoin Cash Testnet Cash SV SV': 'BSV',
    'Bitcoin Cash Testnet Cash SV SV ABC': 'BSV',
    'Bitcoin Cash Testnet Cash SV SV SV': 'BSV',
}
